var ids = [1,2,3,4,5];
console.log(ids);
var reza = ids[3];
console.log(reza);
console.log(ids.length);
ids.push(6);
ids.push(7);
ids.push(8);
ids.push(9);
ids.push(10);
console.log(ids);
console.log(ids.length);
var position = ids.indexOf(9);
console.log(position); 
ids.pop();
console.log(ids);
var thatname = ['salam','kalam','balam','kamal','molom','salom','sorom','norom','dorom','gorom'];
console.log(thatname);
thatname.shift();
thatname.unshift('salamot');
console.log(thatname);
var part = thatname.slice(3);
console.log(part);
var anoPart = thatname.slice(3,7);
console.log(anoPart);
console.log(thatname);
var unkn = thatname.splice(3,7);
console.log(unkn);
console.log(thatname);
console.log(thatname.length);