console.log(128);
var myAge = 20;
console.log(myAge);
console.log(typeof myAge);
var myName = "Mustafizur Rahman Reza";
console.log(myName);
console.log(typeof myName);
var status = false;
console.log(status);
console.log(typeof status);
var hisname = "alom";
var hisname = "mishu";
var hisname = "polash";
var hisName = "mosharrraf";
console.log(hisname);
console.log(typeof hisname);
console.log(hisName);
console.log(typeof hisName);
upName = myName.toUpperCase();
console.log(upName);
