var number1 = 11;
var number2 = 90;
var number3 = number2 + number1;
console.log(number3);
var number4 = number2 * number3;
console.log(number4);
var number5 = number2 / number1; 
console.log(number5);
var number10 = number5 % number4;
console.log(number10);